# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='UserProfile.UserProfile'),
            preserve_default=False,
        ),
    ]
