# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_question_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='isAnswered',
            new_name='is_answered',
        ),
    ]
