# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0003_auto_20151209_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='detail_text',
            new_name='detailText',
        ),
    ]
