# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0004_auto_20151223_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='detailText',
            new_name='detail_text',
        ),
    ]
